require("dotenv").config();
const mongoose = require("mongoose");
const Config = require("../models/Config");

const SEED = [
    {
        key: "brands",
        value: [
            "Mercedes-Benz", "BMW", "Audi", "Volkswagen", "Porsche", "Opel", "Maybach", "Smart", "Alpina", "MAN", "Gumpert", "Borgward", "Wiesmann",
            "Toyota", "Lexus", "Nissan", "Infiniti", "Honda", "Acura", "Mazda", "Subaru", "Mitsubishi", "Suzuki", "Daihatsu", "Isuzu", "Scion", "Datsun", "Mitsuoka",
            "Hyundai", "Kia", "Genesis", "Daewoo", "SsangYong", "Renault Samsung",
            "Ford", "Lincoln", "Chevrolet", "Cadillac", "GMC", "Dodge", "Jeep", "Chrysler", "RAM", "Tesla", "Buick", "Pontiac", "Hummer", "Oldsmobile", "Mercury", "Saturn", "Rivian", "Lucid", "Fisker", "Saleen", "SSC",
            "Ferrari", "Lamborghini", "Maserati", "Fiat", "Alfa Romeo", "Lancia", "Pagani", "Abarth", "Iveco", "De Tomaso",
            "Renault", "Peugeot", "Citroen", "Bugatti", "Alpine", "DS Automobiles",
            "Rolls-Royce", "Bentley", "Aston Martin", "Jaguar", "Land Rover", "MINI", "McLaren", "Lotus", "MG", "Rover", "Vauxhall", "TVR",
            "Volvo", "Saab", "Koenigsegg", "Polestar", "Scania",
            "BYD", "Geely", "Chery", "Great Wall Motors", "Haval", "Zeekr", "NIO", "XPeng", "Li Auto", "Hongqi", "Lynk & Co", "JAC", "FAW", "Dongfeng", "BAIC", "Changan",
            "Tata Motors", "Mahindra", "Maruti Suzuki", "Force Motors", "Hindustan Motors",
            "Lada", "UAZ", "GAZ", "Moskvitch", "Kamaz", "Aurus",
            "Skoda", "Tatra", "SEAT", "Cupra", "Hispano Suiza",
            "Dacia", "ARO", "TOGG", "Anadolu", "Rimac",
            "Spyker", "Donkervoort", "Zenvo", "FSO", "Arrinera", "ZAZ",
            "Troller", "Puma", "Proton", "Perodua", "Holden", "Adam Motors",
            "Iran Khodro", "SAIPA", "VinFast",
            "Hennessey", "Brabus", "Ruf", "Noble", "Ariel", "BAC", "Vector", "Panoz", "SSC Tuatara",
            "Freightliner", "Peterbilt", "Kenworth", "DAF", "Solaris",
            "Jetour", "Avatr", "Omoda", "Jaecoo"
        ]
    },
    {
        key: "models",
        value: {
            "Mercedes-Benz": ["A-Class", "B-Class", "C-Class", "CLA", "CLS", "E-Class", "S-Class", "G-Class", "GLA", "GLB", "GLC", "GLE", "GLS", "SL", "AMG GT", "EQE", "EQS"],
            "BMW": ["1 Series", "2 Series", "3 Series", "4 Series", "5 Series", "7 Series", "X1", "X3", "X5", "X6", "Z4", "i4", "i5", "i7", "IX"],
            "Audi": ["A1", "A3", "A4", "A6", "A8", "Q3", "Q5", "Q7", "Q8", "TT", "R8", "E-Tron"],
            "Volkswagen": ["Golf", "Passat", "Jetta", "Arteon", "Tiguan", "Touareg", "Polo", "Atlas", "ID.4"],
            "Porsche": ["911", "Cayenne", "Macan", "Panamera", "Taycan", "718 Boxster", "718 Cayman"],
            "Opel": ["Astra", "Corsa", "Insignia", "Vectra", "Zafira", "Mokka"],
            "Maybach": ["57", "62", "S-Class Maybach", "GLS Maybach"],
            "Smart": ["Fortwo", "Forfour", "#1", "#3"],
            "Alpina": ["B3", "B5", "XB7", "D3"],
            "MAN": ["TGS", "TGX", "TGM"],
            "Gumpert": ["Apollo"],
            "Borgward": ["BX5", "BX7"],
            "Wiesmann": ["GT", "MF5"],
            "Toyota": ["Camry", "Corolla", "Prius", "RAV4", "Highlander", "Land Cruiser", "Hilux", "Yaris", "Avalon", "CHR", "Tacoma", "Tundra"],
            "Lexus": ["IS", "ES", "GS", "LS", "RX", "GX", "LX", "NX", "UX", "RC", "LC"],
            "Nissan": ["Altima", "Maxima", "Sentra", "Versa", "Pathfinder", "Rogue", "Murano", "Patrol", "370Z", "GT-R", "Leaf"],
            "Infiniti": ["Q50", "Q60", "QX50", "QX60", "QX80"],
            "Honda": ["Civic", "Accord", "CR-V", "HR-V", "Pilot", "Fit", "Odyssey", "Ridgeline", "Insight"],
            "Acura": ["ILX", "TLX", "MDX", "RDX", "NSX"],
            "Mazda": ["Mazda2", "Mazda3", "Mazda6", "CX-3", "CX-5", "CX-9", "MX-5"],
            "Subaru": ["Impreza", "Legacy", "WRX", "Forester", "Outback", "XV", "BRZ"],
            "Mitsubishi": ["Lancer", "Outlander", "Pajero", "Eclipse Cross", "ASX", "Mirage"],
            "Suzuki": ["Swift", "Vitara", "Jimny", "SX4", "Baleno"],
            "Daihatsu": ["Mira", "Terios", "Rocky", "Move"],
            "Isuzu": ["D-Max", "MU-X", "Trooper"],
            "Scion": ["tC", "xB", "FR-S"],
            "Datsun": ["Go", "On-Do"],
            "Mitsuoka": ["Orochi", "Buddy"],
            "Hyundai": ["Elantra", "Sonata", "Tucson", "Santa Fe", "Palisade", "Accent", "Kona", "Ioniq", "Genesis Coupe"],
            "Kia": ["Rio", "Cerato", "K5", "Sportage", "Sorento", "Telluride", "Soul", "EV6"],
            "Genesis": ["G70", "G80", "G90", "GV70", "GV80"],
            "Daewoo": ["Matiz", "Lanos", "Nubira", "Leganza"],
            "SsangYong": ["Rexton", "Korando", "Musso", "Tivoli"],
            "Renault Samsung": ["SM3", "SM5", "QM6"],
            "Ford": ["Focus", "Fusion", "Mustang", "Explorer", "Escape", "F-150", "Edge", "Bronco"],
            "Lincoln": ["Navigator", "Aviator", "MKZ", "Corsair"],
            "Chevrolet": ["Cruze", "Malibu", "Impala", "Camaro", "Tahoe", "Suburban", "Silverado", "Equinox"],
            "Cadillac": ["CTS", "CT5", "Escalade", "XT4", "XT5"],
            "GMC": ["Sierra", "Yukon", "Terrain", "Acadia"],
            "Dodge": ["Charger", "Challenger", "Durango", "Journey", "RAM Van"],
            "Jeep": ["Wrangler", "Grand Cherokee", "Cherokee", "Compass", "Renegade"],
            "Chrysler": ["300", "Pacifica", "Voyager"],
            "RAM": ["1500", "2500", "3500", "TRX"],
            "Tesla": ["Model S", "Model 3", "Model X", "Model Y", "Cybertruck", "Roadster"],
            "Buick": ["Encore", "Enclave", "LaCrosse"],
            "Pontiac": ["GTO", "Firebird", "Vibe"],
            "Hummer": ["H1", "H2", "H3", "EV"],
            "Oldsmobile": ["Alero", "Aurora"],
            "Mercury": ["Grand Marquis", "Milan"],
            "Saturn": ["Ion", "Vue", "Aura"],
            "Rivian": ["R1T", "R1S"],
            "Lucid": ["Air", "Gravity"],
            "Fisker": ["Ocean", "Karma"],
            "Saleen": ["S7", "Mustang"],
            "SSC": ["Ultimate Aero", "Tuatara"],
            "Ferrari": ["488", "458", "F8", "Roma", "SF90", "812 Superfast", "Purosangue"],
            "Lamborghini": ["Huracan", "Aventador", "Urus", "Revuelto"],
            "Maserati": ["Ghibli", "Quattroporte", "Levante", "MC20"],
            "Fiat": ["500", "Panda", "Tipo", "Doblo"],
            "Alfa Romeo": ["Giulia", "Stelvio", "159", "Brera"],
            "Lancia": ["Delta", "Ypsilon", "Thema"],
            "Pagani": ["Zonda", "Huayra", "Utopia"],
            "Abarth": ["595", "695"],
            "Iveco": ["Daily", "Eurocargo"],
            "De Tomaso": ["Pantera", "P72"],
            "Renault": ["Clio", "Megane", "Talisman", "Captur", "Kadjar", "Duster"],
            "Peugeot": ["206", "208", "308", "3008", "5008", "Partner"],
            "Citroen": ["C3", "C4", "C5", "Berlingo", "DS3"],
            "Bugatti": ["Veyron", "Chiron", "Tourbillon"],
            "Alpine": ["A110"],
            "DS Automobiles": ["DS3", "DS4", "DS7"],
            "Rolls-Royce": ["Ghost", "Phantom", "Cullinan", "Wraith"],
            "Bentley": ["Continental GT", "Bentayga", "Flying Spur"],
            "Aston Martin": ["DB11", "DBX", "Vantage", "Vanquish"],
            "Jaguar": ["XE", "XF", "XJ", "F-Pace", "I-Pace"],
            "Land Rover": ["Range Rover", "Defender", "Discovery", "Evoque"],
            "MINI": ["Cooper", "Countryman", "Clubman"],
            "McLaren": ["720S", "765LT", "P1", "Artura"],
            "Lotus": ["Elise", "Exige", "Evora", "Emira", "Eletre"],
            "MG": ["ZS", "HS", "MG5", "Cyberster"],
            "Rover": ["25", "45", "75"],
            "Vauxhall": ["Corsa", "Astra", "Insignia"],
            "TVR": ["Tuscan", "Sagaris"],
            "Volvo": ["S60", "S90", "XC40", "XC60", "XC90", "V60"],
            "Saab": ["9-3", "9-5", "900"],
            "Koenigsegg": ["Jesko", "Regera", "Gemera"],
            "Polestar": ["1", "2", "3", "4"],
            "Scania": ["R-Series", "S-Series"],
            "BYD": ["Han", "Tang", "Seal", "Atto 3", "Dolphin"],
            "Geely": ["Coolray", "Monjaro", "Emgrand"],
            "Chery": ["Tiggo 7", "Tiggo 8", "Arrizo 5"],
            "Great Wall Motors": ["Poer", "Tank 300"],
            "Haval": ["H6", "Jolion", "Dargo"],
            "Zeekr": ["001", "009", "X"],
            "NIO": ["ET5", "ET7", "ES6"],
            "XPeng": ["P7", "G6", "G9"],
            "Li Auto": ["L7", "L8", "L9"],
            "Hongqi": ["H5", "HS5", "E-HS9"],
            "Lynk & Co": ["01", "03", "05"],
            "JAC": ["J7", "T8", "S3"],
            "FAW": ["Bestune T77", "Hongqi H9"],
            "Dongfeng": ["AX7", "Shine"],
            "BAIC": ["BJ40", "X7"],
            "Changan": ["CS35", "CS55", "UNI-T"],
            "Tata Motors": ["Nano", "Harrier", "Safari"],
            "Mahindra": ["Scorpio", "XUV700", "Thar"],
            "Maruti Suzuki": ["Alto", "Swift", "Baleno", "Dzire"],
            "Force Motors": ["Gurkha", "Traveller"],
            "Hindustan Motors": ["Ambassador"],
            "Lada": ["Niva", "Vesta", "Granta"],
            "UAZ": ["Patriot", "Hunter"],
            "GAZ": ["Volga", "Gazelle"],
            "Moskvitch": ["3", "2140"],
            "Kamaz": ["5490", "6520"],
            "Aurus": ["Senat", "Komendant"],
            "Skoda": ["Octavia", "Superb", "Kodiaq", "Fabia", "Rapid"],
            "Tatra": ["Phoenix", "T815"],
            "SEAT": ["Ibiza", "Leon", "Ateca"],
            "Cupra": ["Formentor", "Leon", "Born"],
            "Hispano Suiza": ["Carmen"],
            "Dacia": ["Logan", "Sandero", "Duster"],
            "ARO": ["244"],
            "TOGG": ["T10X"],
            "Anadolu": ["A1"],
            "Rimac": ["Nevera"],
            "Spyker": ["C8"],
            "Donkervoort": ["D8"],
            "Zenvo": ["TSR-S"],
            "FSO": ["Polonez"],
            "Arrinera": ["Hussarya"],
            "ZAZ": ["Tavria", "Lanos"],
            "Troller": ["T4"],
            "Puma": ["GT"],
            "Proton": ["Saga", "X70"],
            "Perodua": ["Myvi", "Axia"],
            "Holden": ["Commodore", "Colorado"],
            "Adam Motors": ["2EV"],
            "Iran Khodro": ["Samand", "Dena"],
            "SAIPA": ["Tiba", "Quick"],
            "VinFast": ["VF8", "VF9"],
            "Hennessey": ["Venom F5"],
            "Brabus": ["Rocket 900", "G800"],
            "Ruf": ["CTR", "Rt12"],
            "Noble": ["M400", "M600"],
            "Ariel": ["Atom", "Nomad"],
            "BAC": ["Mono"],
            "Vector": ["W8"],
            "Panoz": ["Esperante"],
            "SSC Tuatara": ["Tuatara"],
            "Freightliner": ["Cascadia", "M2 106"],
            "Peterbilt": ["389", "579"],
            "Kenworth": ["T680", "W900"],
            "DAF": ["XF", "CF"],
            "Solaris": ["Urbino"],
            "Jetour": ["X70", "X90", "Dashing"],
            "Avatr": ["11", "12"],
            "Omoda": ["C5", "E5"],
            "Jaecoo": ["J7", "J8"]
        }
    },
    {
        key: "fuels",
        value: ["Petrol", "Electric", "Hybrid", "Diesel"]
    },
    {
        key: "transmissions",
        value: ["Automatic", "Manual"]
    },
    {
        key: "allSpecs",
        value: [
            { key: "year",         label: "YEAR",         icon: "/specifications/calendar1.png" },
            { key: "mileage",      label: "MILEAGE",      icon: "/specifications/mileage2.png" },
            { key: "engine",       label: "ENGINE",       icon: "/specifications/engine1.png" },
            { key: "power",        label: "POWER",        icon: "/specifications/hp2.png" },
            { key: "fuel",         label: "FUEL",         icon: "/specifications/fuel.png" },
            { key: "transmission", label: "TRANSMISSION", icon: "/specifications/transmission.png" },
            { key: "drivetrain",   label: "DRIVETRAIN",   icon: "/specifications/drivetrain.png" },
            { key: "exterior",     label: "EXTERIOR",     icon: "/specifications/exinterior.png" },
            { key: "interior",     label: "INTERIOR",     icon: "/specifications/exinterior.png" },
            { key: "vin",          label: "VIN",          icon: "/specifications/vin.png" },
            { key: "steering",     label: "STEERING",     icon: "/specifications/steering.png" },
            { key: "customs",      label: "CUSTOMS",      icon: "/specifications/customs.png" },
            { key: "owners",       label: "OWNERS",       icon: "/specifications/owners.png" },
            { key: "seats",        label: "SEATS",        icon: "/specifications/seats.png" },
        ]
    },
    {
        key: "equipmentCats",
        value: [
            {
                key: "comfort", label: "Comfort", icon: "/sparkles1.png",
                suggestions: ["Heated seats","Ventilated seats","Ambient lighting","Panoramic roof","Memory seats","4-zone climate","Massage seats","Keyless entry"]
            },
            {
                key: "technology", label: "Technology", icon: "/technology.png",
                suggestions: ["Apple CarPlay","Android Auto","Heads-Up Display","360° Camera","Premium navigation","Wireless charging","Premium sound","Digital cockpit"]
            },
            {
                key: "safety", label: "Safety", icon: "/icons/shield.png",
                suggestions: ["Lane keep assist","Blind spot monitor","Adaptive cruise","Parking sensors","Auto emergency brake","Driver attention","Night vision","Rear camera"]
            },
            {
                key: "performance", label: "Performance", icon: "/performance.png",
                suggestions: ["Sport package","Adaptive suspension","Sport exhaust","Launch control","Carbon ceramic brakes","Performance tires","Sport differential","Track mode"]
            },
        ]
    },
];

mongoose.connect(process.env.MONGO_URI).then(async () => {
    for (const item of SEED) {
        await Config.findOneAndUpdate(
            { key: item.key },
            { value: item.value },
            { upsert: true }
        );
        console.log(`✓ seeded: ${item.key}`);
    }
    console.log("Done.");
    process.exit(0);
}).catch(err => {
    console.error(err);
    process.exit(1);
});